# Generated by Django 6.0.3 on 2026-03-07 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')])),
                ('class_type', models.IntegerField(choices=[(0, 'Military'), (1, 'Civilian'), (2, 'Stealth'), (3, 'Industrial'), (4, 'Competition')])),
                ('durability_hp', models.IntegerField(blank=True, null=True)),
                ('power_draw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thermal_output', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('em_signature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ir_signature', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_loot_only', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, 'In Game'), (1, 'Planned'), (2, 'Removed')])),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'component',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'component categories',
                'db_table': 'component_category',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentSpecCooler',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cooling_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'component_spec_cooler',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentSpecMissile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('missile_type', models.IntegerField(choices=[(0, 'Missile'), (1, 'Torpedo'), (2, 'Bomb'), (3, 'Rocket')])),
                ('tracking_type', models.IntegerField(choices=[(0, 'Infrared'), (1, 'Electromagnetic'), (2, 'Cross-Section'), (3, 'None')])),
                ('damage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lock_time_s', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('speed_ms', models.IntegerField(blank=True, null=True)),
                ('range_m', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'component_spec_missile',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentSpecPowerPlant',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('power_output', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'component_spec_power_plant',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentSpecQuantumDrive',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantum_speed_mps', models.IntegerField(blank=True, null=True)),
                ('quantum_speed_c', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('spool_time_s', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_consumption_lmkm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cooldown_time_s', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('calibration_speed', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('drive_stage', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'component_spec_quantum_drive',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentSpecShield',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shield_hp', models.IntegerField(blank=True, null=True)),
                ('regen_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('regen_delay_s', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ballistic_resistance', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('energy_resistance', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('distortion_resistance', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'component_spec_shield',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentSpecWeapon',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weapon_type', models.IntegerField(choices=[(0, 'Cannon'), (1, 'Repeater'), (2, 'Gatling'), (3, 'Scattergun'), (4, 'Distortion'), (5, 'Laser')])),
                ('damage_type', models.IntegerField(choices=[(0, 'Energy'), (1, 'Ballistic'), (2, 'Distortion'), (3, 'Mixed')])),
                ('fire_rate_rpm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('damage_per_shot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('projectile_speed_ms', models.IntegerField(blank=True, null=True)),
                ('range_m', models.IntegerField(blank=True, null=True)),
                ('ammo_capacity', models.IntegerField(blank=True, null=True)),
                ('pellets_per_shot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'component_spec_weapon',
                'abstract': False,
            },
        ),
    ]
