# Generated by Django 6.0.3 on 2026-03-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0001_initial'),
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='manufacturer.manufacturer'),
        ),
        migrations.AddField(
            model_name='componentcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='component.componentcategory'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='component.componentcategory'),
        ),
        migrations.AddField(
            model_name='componentspeccooler',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_cooler', to='component.component'),
        ),
        migrations.AddField(
            model_name='componentspecmissile',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_missile', to='component.component'),
        ),
        migrations.AddField(
            model_name='componentspecpowerplant',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_power_plant', to='component.component'),
        ),
        migrations.AddField(
            model_name='componentspecquantumdrive',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_quantum_drive', to='component.component'),
        ),
        migrations.AddField(
            model_name='componentspecshield',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_shield', to='component.component'),
        ),
        migrations.AddField(
            model_name='componentspecweapon',
            name='component',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec_weapon', to='component.component'),
        ),
        migrations.AddIndex(
            model_name='component',
            index=models.Index(fields=['component_category', 'size', 'grade'], name='component_compone_f6afd7_idx'),
        ),
    ]
