# Generated by Django 6.0.3 on 2026-03-07 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorPiece',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('slot', models.IntegerField(choices=[(0, 'Helmet'), (1, 'Chest'), (2, 'Arms'), (3, 'Legs'), (4, 'Backpack')])),
                ('armor_type', models.IntegerField(choices=[(0, 'Light'), (1, 'Medium'), (2, 'Heavy')])),
                ('description', models.TextField(blank=True)),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'armor_piece',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('clothing_type', models.IntegerField(choices=[(0, 'Jacket'), (1, 'Shirt'), (2, 'Pants'), (3, 'Shoes'), (4, 'Gloves'), (5, 'Hat'), (6, 'Glasses'), (7, 'Backpack'), (8, 'Accessory')])),
                ('description', models.TextField(blank=True)),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'clothing',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalArmor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('armor_type', models.IntegerField(choices=[(0, 'Light'), (1, 'Medium'), (2, 'Heavy')])),
                ('armor_category', models.IntegerField(choices=[(0, 'Combat'), (1, 'Specialist'), (2, 'Utility'), (3, 'Support')])),
                ('damage_reduction_ballistic', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('damage_reduction_energy', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('temperature_resistance', models.CharField(blank=True, max_length=50)),
                ('inventory_slots', models.IntegerField(blank=True, null=True)),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('rarity', models.IntegerField(choices=[(0, 'Common'), (1, 'Uncommon'), (2, 'Rare'), (3, 'Very Rare')])),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'personal_armor',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalWeapon',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('weapon_class', models.IntegerField(choices=[(0, 'Pistol'), (1, 'SMG'), (2, 'Assault Rifle'), (3, 'Shotgun'), (4, 'Sniper Rifle'), (5, 'LMG'), (6, 'Launcher'), (7, 'Railgun'), (8, 'Crossbow'), (9, 'Knife'), (10, 'Melee')])),
                ('damage_type', models.IntegerField(choices=[(0, 'Ballistic'), (1, 'Energy'), (2, 'Plasma'), (3, 'Distortion'), (4, 'Mixed')])),
                ('fire_modes', models.CharField(blank=True, max_length=100)),
                ('fire_rate_rpm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('damage_per_shot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_range_m', models.IntegerField(blank=True, null=True)),
                ('max_range_m', models.IntegerField(blank=True, null=True)),
                ('magazine_size', models.IntegerField(blank=True, null=True)),
                ('ammo_type', models.CharField(blank=True, max_length=50)),
                ('has_optic_slot', models.BooleanField()),
                ('has_barrel_slot', models.BooleanField()),
                ('has_underbarrel_slot', models.BooleanField()),
                ('mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('rarity', models.IntegerField(choices=[(0, 'Common'), (1, 'Uncommon'), (2, 'Rare'), (3, 'Very Rare'), (4, 'Loot Only')])),
                ('status', models.IntegerField(choices=[(0, 'In Game'), (1, 'Planned')])),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'personal_weapon',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tool_type', models.IntegerField(choices=[(0, 'Multi-Tool'), (1, 'Med Pen'), (2, 'OxyPen'), (3, 'Flare'), (4, 'Tractor Beam Attachment'), (5, 'Mining Attachment'), (6, 'Repair Attachment'), (7, 'Salvage Attachment')])),
                ('description', models.TextField(blank=True)),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'tool',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Undersuit',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('temperature_range', models.CharField(blank=True, max_length=100)),
                ('has_eva_capability', models.BooleanField()),
                ('inventory_slots', models.IntegerField(blank=True, null=True)),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'undersuit',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponAttachment',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('attachment_type', models.IntegerField(choices=[(0, 'Optic'), (1, 'Barrel'), (2, 'Underbarrel'), (3, 'Magazine')])),
                ('description', models.TextField(blank=True)),
                ('magnification', models.CharField(blank=True, max_length=20)),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'weapon_attachment',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeaponAttachmentCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.IntegerField(choices=[(0, 'Optic'), (1, 'Barrel'), (2, 'Underbarrel')])),
            ],
            options={
                'db_table': 'weapon_attachment_compatibility',
            },
        ),
    ]
