# Generated by Django 6.0.3 on 2026-03-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorpiece',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armor_pieces', to='manufacturer.manufacturer'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_items', to='manufacturer.manufacturer'),
        ),
        migrations.AddField(
            model_name='personalarmor',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_armors', to='manufacturer.manufacturer'),
        ),
        migrations.AddField(
            model_name='armorpiece',
            name='armor_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='equipment.personalarmor'),
        ),
        migrations.AddField(
            model_name='personalweapon',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_weapons', to='manufacturer.manufacturer'),
        ),
        migrations.AddField(
            model_name='tool',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='manufacturer.manufacturer'),
        ),
        migrations.AddField(
            model_name='undersuit',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undersuits', to='manufacturer.manufacturer'),
        ),
        migrations.AddField(
            model_name='weaponattachment',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon_attachments', to='manufacturer.manufacturer'),
        ),
        migrations.AddField(
            model_name='weaponattachmentcompatibility',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapon_compatibilities', to='equipment.weaponattachment'),
        ),
        migrations.AddField(
            model_name='weaponattachmentcompatibility',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment_compatibilities', to='equipment.personalweapon'),
        ),
        migrations.AlterUniqueTogether(
            name='weaponattachmentcompatibility',
            unique_together={('weapon', 'attachment')},
        ),
    ]
