# Generated by Django 6.0.3 on 2026-03-07 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityCategory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='economy.commoditycategory')),
            ],
            options={
                'verbose_name_plural': 'commodity categories',
                'db_table': 'commodity_category',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('legality', models.IntegerField(choices=[(0, 'Legal'), (1, 'Illegal'), (2, 'Restricted'), (3, 'Contraband')])),
                ('base_price_auec', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_mineable', models.BooleanField()),
                ('is_tradeable', models.BooleanField(default=True)),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('commodity_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='economy.commoditycategory')),
            ],
            options={
                'verbose_name_plural': 'commodities',
                'db_table': 'commodity',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MiningResource',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('instability', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('resistance', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('optimal_charge_window', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mining_resources', to='economy.commodity')),
            ],
            options={
                'db_table': 'mining_resource',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('shop_type', models.IntegerField(choices=[(0, 'Weapons'), (1, 'Armor'), (2, 'Components'), (3, 'Clothing'), (4, 'Commodity'), (5, 'Food'), (6, 'General'), (7, 'Ship Dealer'), (8, 'Vehicle Rental'), (9, 'Refinery')])),
                ('description', models.TextField(blank=True)),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='universe.location')),
            ],
            options={
                'db_table': 'shop',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommodityPriceEntry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.IntegerField(choices=[(0, 'Buy'), (1, 'Sell')])),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField()),
                ('supply_demand_status', models.CharField(blank=True, max_length=50)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_entries', to='economy.commodity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_prices', to='universe.location')),
            ],
            options={
                'verbose_name_plural': 'commodity price entries',
                'db_table': 'commodity_price_entry',
                'abstract': False,
                'indexes': [models.Index(fields=['commodity', 'location', 'transaction_type'], name='commodity_p_commodi_5eb22d_idx'), models.Index(fields=['recorded_at'], name='commodity_p_recorde_a17a94_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='economy.shop')),
            ],
            options={
                'verbose_name_plural': 'shop inventories',
                'db_table': 'shop_inventory',
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='shop_invent_content_16ea2b_idx')],
            },
        ),
    ]
