from enum import StrEnum


class ErrorCodes(StrEnum):
    INIT_FAILED = "INIT_FAILED"
    UNAUTHORIZED = "UNAUTHORIZED"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

    # Authentication
    WRONG_CREDENTIALS = "WRONG_CREDENTIALS"
    MISSING_REFRESH_TOKEN = "MISSING_REFRESH_TOKEN"
    MISSING_ACCESS_TOKEN = "MISSING_ACCESS_TOKEN"
    BLACKLISTED_TOKEN = "BLACKLISTED_TOKEN"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    EXPIRED_TOKEN = "EXPIRED_TOKEN"

    # Not found
    USER_NOT_FOUND = "USER_NOT_FOUND"
