# Generated by Django 6.0.3 on 2026-03-07 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('faction_type', models.IntegerField(choices=[(0, 'Government'), (1, 'Corporation'), (2, 'Military'), (3, 'Pirate'), (4, 'Criminal'), (5, 'Religious'), (6, 'Trade Guild'), (7, 'Other')])),
                ('description', models.TextField(blank=True)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('is_lawful', models.BooleanField(blank=True, null=True)),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'faction',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoreArticle',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('content', models.TextField(blank=True)),
                ('category', models.IntegerField(choices=[(0, 'History'), (1, 'Technology'), (2, 'Culture'), (3, 'Politics'), (4, 'Science'), (5, 'Biography'), (6, 'Event'), (7, 'Location'), (8, 'Species')])),
                ('source', models.IntegerField(choices=[(0, 'Galactapedia'), (1, 'Comm-Link'), (2, 'Jump Point'), (3, "Writer's Guide"), (4, 'Spectrum')])),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('lore_date', models.CharField(blank=True, max_length=50)),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'lore_article',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MissionType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.IntegerField(choices=[(0, 'Combat'), (1, 'Trade'), (2, 'Mining'), (3, 'Exploration'), (4, 'Delivery'), (5, 'Investigation'), (6, 'Rescue'), (7, 'Mercenary'), (8, 'Piracy'), (9, 'Salvage')])),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'mission_type',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('classification', models.IntegerField(choices=[(0, 'Sentient'), (1, 'Developing'), (2, 'Extinct')])),
                ('description', models.TextField(blank=True)),
                ('homeworld', models.CharField(blank=True, max_length=100)),
                ('government_type', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('lifespan', models.CharField(blank=True, max_length=50)),
                ('physical_description', models.TextField(blank=True)),
                ('cultural_notes', models.TextField(blank=True)),
                ('relation_to_humans', models.IntegerField(choices=[(0, 'Allied'), (1, 'Neutral'), (2, 'Hostile'), (3, 'Unknown'), (4, 'Assimilated')])),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'species',
                'db_table': 'species',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MissionGiver',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_givers', to='lore.faction')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_givers', to='universe.location')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_givers', to='lore.species')),
            ],
            options={
                'db_table': 'mission_giver',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_reputation_required', models.IntegerField(blank=True, null=True)),
                ('reward_auec_min', models.IntegerField(blank=True, null=True)),
                ('reward_auec_max', models.IntegerField(blank=True, null=True)),
                ('reward_reputation', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard'), (3, 'Very Hard')])),
                ('is_lawful', models.BooleanField(blank=True, null=True)),
                ('is_group_recommended', models.BooleanField()),
                ('is_chain_mission', models.BooleanField()),
                ('chain_order', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'In Game'), (1, 'Planned'), (2, 'Removed')])),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='universe.location')),
                ('reputation_faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_missions', to='lore.faction')),
                ('star_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='universe.starsystem')),
                ('mission_giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='lore.missiongiver')),
                ('mission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='lore.missiontype')),
            ],
            options={
                'db_table': 'mission',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='faction',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factions', to='lore.species'),
        ),
        migrations.CreateModel(
            name='LoreArticleEntity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.IntegerField(choices=[(0, 'Star System'), (1, 'Celestial Body'), (2, 'Location'), (3, 'Species'), (4, 'Faction'), (5, 'Vehicle'), (6, 'Manufacturer'), (7, 'Person')])),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('lore_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='lore.lorearticle')),
            ],
            options={
                'db_table': 'lore_article_entity',
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='lore_articl_content_d72acd_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpeciesRelation',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.IntegerField(choices=[(0, 'Allied'), (1, 'Neutral'), (2, 'Tense'), (3, 'Hostile'), (4, 'War'), (5, 'Trade Only'), (6, 'Unknown')])),
                ('description', models.TextField(blank=True)),
                ('species_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_a', to='lore.species')),
                ('species_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_b', to='lore.species')),
            ],
            options={
                'db_table': 'species_relation',
                'abstract': False,
                'unique_together': {('species_a', 'species_b')},
            },
        ),
    ]
