# Generated by Django 6.0.3 on 2026-03-07 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('component', '0001_initial'),
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleTag',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.IntegerField(choices=[(0, 'Role'), (1, 'Gameplay'), (2, 'Special')])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'vehicle_tag',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('series', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.IntegerField(choices=[(0, 'Spaceship'), (1, 'Ground Vehicle'), (2, 'Gravlev')])),
                ('size_class', models.IntegerField(choices=[(0, 'Snub'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Capital')])),
                ('focus_primary', models.CharField(blank=True, max_length=100)),
                ('focus_secondary', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('lore_description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(0, 'Flight Ready'), (1, 'In Concept'), (2, 'In Production'), (3, 'Announced'), (4, 'Lore Only')])),
                ('is_alien', models.BooleanField()),
                ('min_crew', models.IntegerField(blank=True, null=True)),
                ('max_crew', models.IntegerField(blank=True, null=True)),
                ('cargo_capacity_scu', models.IntegerField(blank=True, null=True)),
                ('length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('beam_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('mass_kg', models.IntegerField(blank=True, null=True)),
                ('combat_speed_ms', models.IntegerField(blank=True, null=True)),
                ('max_speed_ms', models.IntegerField(blank=True, null=True)),
                ('scm_speed_ms', models.IntegerField(blank=True, null=True)),
                ('hydrogen_fuel_capacity', models.IntegerField(blank=True, null=True)),
                ('quantum_fuel_capacity', models.IntegerField(blank=True, null=True)),
                ('pledge_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingame_price_auec', models.IntegerField(blank=True, null=True)),
                ('warbond_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pledge_availability', models.IntegerField(choices=[(0, 'Permanent'), (1, 'Limited'), (2, 'Concierge'), (3, 'Event'), (4, 'Not Available')])),
                ('insurance_claim_time_s', models.IntegerField(blank=True, null=True)),
                ('expedited_claim_time_s', models.IntegerField(blank=True, null=True)),
                ('expedited_claim_cost', models.IntegerField(blank=True, null=True)),
                ('has_quantum_drive', models.BooleanField(default=True)),
                ('has_bed', models.BooleanField()),
                ('has_interior', models.BooleanField()),
                ('can_carry_vehicle', models.BooleanField()),
                ('pad_size', models.IntegerField(choices=[(0, 'XS'), (1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'XL'), (5, 'Hangar')])),
                ('added_in_patch', models.CharField(blank=True, max_length=20)),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('brochure_url', models.URLField(blank=True, max_length=500)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='manufacturer.manufacturer')),
            ],
            options={
                'db_table': 'vehicle',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleHardpoint',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hardpoint_name', models.CharField(max_length=100)),
                ('hardpoint_type', models.IntegerField(choices=[(0, 'Weapon'), (1, 'Missile Rack'), (2, 'Turret'), (3, 'Power Plant'), (4, 'Cooler'), (5, 'Shield Generator'), (6, 'Quantum Drive'), (7, 'Radar'), (8, 'Computer'), (9, 'Life Support'), (10, 'Mining Laser'), (11, 'Salvage Head'), (12, 'Tractor Beam'), (13, 'Fuel Pod'), (14, 'Cargo Grid'), (15, 'Vehicle Module'), (16, 'Utility')])),
                ('size', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('is_gimbal', models.BooleanField()),
                ('is_turret', models.BooleanField()),
                ('is_manned', models.BooleanField()),
                ('is_remote', models.BooleanField()),
                ('mount_type', models.IntegerField(choices=[(0, 'Fixed'), (1, 'Gimbal'), (2, 'Turret'), (3, 'Remote Turret'), (4, 'Unmanned Turret')])),
                ('default_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_on_hardpoints', to='component.component')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardpoints', to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_hardpoint',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('image_type', models.IntegerField(choices=[(0, 'Exterior'), (1, 'Interior'), (2, 'Cockpit'), (3, 'Cargo'), (4, 'Brochure'), (5, 'Concept Art'), (6, 'Screenshot')])),
                ('is_primary', models.BooleanField()),
                ('sort_order', models.IntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_image',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleLoanerEntry',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loaner_context', models.IntegerField(choices=[(0, 'Persistent Universe'), (1, 'Arena Commander')])),
                ('loaner_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaner_entries_as_loaner', to='vehicle.vehicle')),
                ('pledged_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaner_entries_as_pledged', to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_loaner_entry',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehiclePaint',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('source', models.IntegerField(choices=[(0, 'Pledge'), (1, 'In-Game Purchase'), (2, 'Event'), (3, 'Subscriber'), (4, 'Referral')])),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_auec', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paints', to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_paint',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleTagAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='vehicle.vehicletag')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_tag_assignment',
            },
        ),
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.IntegerField(choices=[(0, 'Variant'), (1, 'Upgrade'), (2, 'Edition'), (3, 'Military/Civilian')])),
                ('base_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_as_base', to='vehicle.vehicle')),
                ('variant_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_as_variant', to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'vehicle_variant',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['manufacturer', 'status'], name='vehicle_manufac_33941c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['size_class'], name='vehicle_size_cl_e82058_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicletagassignment',
            unique_together={('vehicle', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclevariant',
            unique_together={('base_vehicle', 'variant_vehicle')},
        ),
    ]
