# Generated by Django 6.0.3 on 2026-03-07 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('manufacturer_type', models.IntegerField(choices=[(0, 'Ship'), (1, 'Component'), (2, 'Weapon'), (3, 'Personal Weapon'), (4, 'Armor'), (5, 'Clothing'), (6, 'Multi')])),
                ('origin', models.CharField(blank=True, max_length=100)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('founding_date_lore', models.CharField(blank=True, max_length=50)),
                ('is_alien', models.BooleanField()),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('wiki_url', models.URLField(blank=True, max_length=500)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers', to='lore.species')),
            ],
            options={
                'db_table': 'manufacturer',
                'abstract': False,
            },
        ),
    ]
