# Generated by Django 6.0.3 on 2026-03-07 19:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('api_url', models.URLField(blank=True, max_length=500)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_source',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_live', models.BooleanField()),
                ('is_ptu', models.BooleanField()),
                ('patch_notes_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'game_version',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('tag_group', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'db_table': 'tag',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=500)),
                ('media_type', models.IntegerField(choices=[(0, 'Image'), (1, 'Video'), (2, 'PDF')])),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('object_id', models.UUIDField()),
                ('sort_order', models.IntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'media',
                'abstract': False,
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='media_content_a5c40c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Taggable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggables', to='core.tag')),
            ],
            options={
                'db_table': 'taggable',
                'unique_together': {('tag', 'content_type', 'object_id')},
            },
        ),
    ]
